### ISSUE TITLE
Build#25 - Addons broken

### ISSUE THREAD

**Issue by MidnightSugar** [t00thpick1/mcMMO#4]
`01.01 04:23:17 [Server] ERROR Error occurred while enabling mcMMOAction v2.3.2 (Is it up to date?) 01.01 04:23:17 [Server] INFO java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType 01.01 04:23:17 [Server] INFO at com.github.games647.mcmmoaction.Configuration.loadMessages(Configuration.java:88) ~[?:?] 01.01 04:23:17 [Server] INFO at com.github.games647.mcmmoaction.Configuration.load(Configuration.java:54) ~[?:?] 01.01 04:23:17 [Server] INFO at com.github.games647.mcmmoaction.mcMMOAction.onEnable(mcMMOAction.java:55) ~[?:?] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 01.01 04:23:17 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.datatypes.skills.SkillType 01.01 04:23:17 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191] 01.01 04:23:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191] 01.01 04:23:17 [Server] INFO ... 14 more 01.01 04:23:17 [Server] INFO [HeadDatabase] Enabling HeadDatabase v4.6.2 01.01 04:23:17 [Server] INFO [HeadDatabase] Economy succesfully setup! 01.01 04:23:17 [Server] INFO [McMMOExtras] Enabling McMMOExtras v5.3.2 01.01 04:23:17 [Server] ERROR Error occurred while enabling McMMOExtras v5.3.2 (Is it up to date?) 01.01 04:23:17 [Server] INFO java.lang.NoClassDefFoundError: com/gmail/nossr50/datatypes/skills/SkillType 01.01 04:23:17 [Server] INFO at me.xeroun.mcmmoextras.McMMOExtras.initializeBarAPI(McMMOExtras.java:137) ~[?:?] 01.01 04:23:17 [Server] INFO at me.xeroun.mcmmoextras.McMMOExtras.onEnable(McMMOExtras.java:54) ~[?:?] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 01.01 04:23:17 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.datatypes.skills.SkillType 01.01 04:23:17 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-518206a-5be2ddc] 01.01 04:23:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191] 01.01 04:23:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191] 01.01 04:23:17 [Server] INFO ... 13 more`

**Comment by t00thpick1** [comment]
Hi!  We have just split mcMMO into two development tracks.   mcMMO Classic (Which will continue to support and fix the current mcMMO experience)   and mcMMO 2, which is evolving the mcMMO experience to fit better with the newer minecraft feel.   mcMMO 2 has made some API updates that have broken 3rd party plugins.  I would suggest returning to mcMMO Classic until said 3rd party plugins have updated.   It may be that you downloaded a build off the dev build CI,  we were undergoing some structural changes for a bit and some of that was in flux and you may have downloaded a mcMMO 2 build without realizing it.

**Comment by MidnightSugar** [comment]
Would you consider adding built in support for displaying skill messages through the action bar instead of chat? I believe this should be a default feature in the new mcmmo, because chat gets very spammy otherwise.

**Comment by t00thpick1** [comment]
Since it is already possible via the API, no not in mcMMO Classic, however I can add a config option to disable to chat messages so that you can choose which one you want
